# Generated by Django 4.1.5 on 2023-01-19 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='user_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
